import { PublicLayout } from "@/components/layout/PublicLayout";

const features = [
  ["Private studio", "Write, edit, publish, organize, and manage articles from a protected editorial workspace."],
  ["Multilingual entries", "Keep multiple language versions connected to the same article and URL structure."],
  ["Media", "Upload cover and article images through protected storage."],
  ["Publishing", "Archives, tags, RSS, sitemap, canonical metadata, and structured article data are generated by the app."],
];

export default function Platform() {
  return (
    <PublicLayout>
      <div className="max-w-3xl mx-auto py-10 md:py-14">
        <p className="text-sm uppercase tracking-[0.2em] text-primary mb-4">Under the hood</p>
        <h1 className="text-4xl md:text-5xl font-display font-medium text-foreground mb-6">The journal is simple. The system behind it is not.</h1>
        <p className="text-lg text-muted-foreground leading-relaxed mb-10">
          ATLAS is a real publishing application rather than a static collection of pages. I built both the reading experience and the tools used to publish it.
        </p>
        <div className="grid md:grid-cols-2 gap-5">
          {features.map(([title, body]) => (
            <section key={title} className="rounded-2xl border border-border/60 p-6 bg-card/40">
              <h2 className="font-display text-xl mb-3">{title}</h2>
              <p className="text-muted-foreground leading-relaxed">{body}</p>
            </section>
          ))}
        </div>
      </div>
    </PublicLayout>
  );
}
